  /// \file Event.h
/*
 *
 * Event.h header template automatically generated by a class generator
 * Creation date : ven. mars 18 2016
 *
 * This file is part of Trivent libraries.
 * 
 * Trivent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * Trivent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Trivent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef EVENT_H
#define EVENT_H

// -- trivent headers
#include "Unit.h"

// -- std headers
#include <map>
#include <string>
#include <vector>

namespace trivent
{

/** 
 *  @brief  Event class
 */ 
class Event 
{
public:
	/**
	 *  @brief  Constructor
	 */
	Event();

	/**
	 *  @brief  Destructor
	 */
	~Event();

	/**
	 *  @brief  Clear the event content
	 */
	void clear(bool deepClean = true);

	/**
	 *  @brief  Add a single unit to target collection
	 */
	void addUnit(const std::string &collectionName, Unit *pUnit);

	/**
	 *  @brief  Add multiple units to target collection
	 */
	void addUnits(const std::string &collectionName, const UnitSet &unitSet);

	/**
	 *  @brief  Remove a single unit from the target collection
	 */
	void removeUnit(const std::string &collectionName, Unit *pUnit, bool callDelete = true);

	/**
	 *  @brief  Remove units from the target collection
	 */
	void removeUnits(const std::string &collectionName, const UnitSet &unitSet, bool callDelete = true);

	/**
	 *  @brief  Get the unit list saved as the target collection name
	 */
	void getUnits(const std::string &collectionName, UnitSet &unitSet) const;

	/**
	 *  @brief  Get the available collection names
	 */
	std::vector<std::string> getCollectionNames() const;

private:
	typedef std::map<const std::string, UnitSet> UnitCollectionMap;

	UnitCollectionMap                    m_unitCollectionMap;
}; 

} 

#endif  //  EVENT_H
