  /// \file Unit.cc
/*
 *
 * Unit.cc source template automatically generated by a class generator
 * Creation date : ven. mars 18 2016
 *
 * This file is part of Trivent libraries.
 * 
 * Trivent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * Trivent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Trivent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

// -- trivent headers
#include "Unit.h"

namespace trivent
{

Unit::Unit(uint64_t time, void *pUserInput) :
		m_time(time),
		m_pUserInput(pUserInput)
{
	/* nop */
}

//-------------------------------------------------------------------------------------------------

uint64_t Unit::getTime() const
{
	return m_time;
}

//-------------------------------------------------------------------------------------------------

void *Unit::getUserInput() const
{
	return m_pUserInput;
}

//-------------------------------------------------------------------------------------------------

const std::string &Unit::getCollectionName() const
{
	return m_collectionName;
}

//-------------------------------------------------------------------------------------------------

void Unit::setCollectionName(const std::string &collectionName)
{
	m_collectionName = collectionName;
}

} 

